config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :head_hunters, path: 'head_hunter_accounts', controllers: {
    registrations: 'hunter/registrations',
    sessions: 'hunter/sessions'
  }
  devise_for :job_seekers, path: 'job_seeker_accounts', controllers: {
    registrations: 'seeker/registrations',
    sessions: 'seeker/sessions'
  }

  root 'home#index'

  namespace :hunter do
    root 'dashboard#index'
    get '/dashboard', to: 'dashboard#index', as: :dashboard

    resources :jobs, only: %i[index show new create] do
      patch :retire
    end

    resources :applications, only: %i[index show] do
      patch :standout
      get   :rejection
      patch :reject

      resources :offers, only: %i[new create]
    end

    resources :applicants, only: %i[index show] do
      post :comment
    end

    resources :offers, only: %i[index show]
  end

  namespace :seeker do
    root 'dashboard#index'
    get '/dashboard', to: 'dashboard#index', as: :dashboard

    resources :profiles, only: %i[new create]
    get '/profile', to: 'profiles#show', as: :show_profile
    get '/profile/edit', to: 'profiles#edit', as: :edit_profile
    patch '/profile', to: 'profiles#update', as: :update_profile

    resources :jobs, only: %i[index show] do
      resources :applications, only: %i[new create]
    end

    resources :applications, only: %i[index show]
    resources :offers, only: %i[index show] do
      patch :accept
      patch :reject
    end
  end
end

app/models/job.rb
# frozen_string_literal: true

class Job < ApplicationRecord
  BRAZILIAN_MINIMUM_WAGE = 1039

  belongs_to :head_hunter
  has_many :applications, dependent: :destroy, class_name: Job::Application.name
  has_many :applicants, through: :applications, source: :job_seeker

  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 50 }
  validates :skills, presence: true
  validates :salary_floor,
            numericality: { only_integer: true,
                            greater_than_or_equal_to: BRAZILIAN_MINIMUM_WAGE,
                            less_than: 50_000 }, presence: true
  validates :salary_roof, numericality: { only_integer: true, less_than: 50_200 },
                          presence: true
  validate :whether_the_salary_range_is_reasonable
  validates :position, presence: true
  validates :location, presence: true
  validates :retired, inclusion: { in: [true, false] }
  validates :expires_on, presence: true, format: { with: ApplicationHelper::DATE_REGEX }
  validate :whether_it_expires_in_a_month
  validates :head_hunter, presence: true

  before_save :titleize_attributes

  default_scope -> { order expires_on: :desc }
  scope :created_by, ->(head_hunter) { where head_hunter: head_hunter }
  scope :active, -> { where "retired = FALSE AND expires_on > DATE('now')" }
  scope :by_title_or_description, lambda { |search|
                                    where 'title like ? OR description like ?',
                                          "%#{search}%", "%#{search}%"
                                  }

  def expired?
    expires_on < Date.today
  end

  def active?
    return false if expired?

    !retired
  end

  def retire!
    update_attribute :retired, true
  end

  def minimum_wage
    BRAZILIAN_MINIMUM_WAGE
  end

  def ongoing_applications
    applications.where rejection_feedback: nil
  end

  private

  def whether_the_salary_range_is_reasonable
    return if salary_floor.nil?
    return if salary_roof && salary_roof >= salary_floor + 200

    errors.add :salary_roof, :greater_than_or_equal_to, count: salary_floor + 200
  end

  def whether_it_expires_in_a_month
    return if expires_on_is_at_least_one_month_away?

    errors.add :expires_on, :before_one_month
  end

  def expires_on_is_at_least_one_month_away?
    expires_on && 1.month.from_now <= expires_on
  end

  def titleize_attributes
    self.title = title.titleize
    self.skills = skills.titleize
    self.position = position.titleize
    self.location = location.titleize
  end
end

app/models/job/application.rb
# frozen_string_literal: true

class Job
  class Application < ActiveRecord::Base
    belongs_to :job
    belongs_to :job_seeker

    has_one :head_hunter, through: :job

    has_many :offers, dependent: :destroy, class_name: Job::Application::Offer.name,
                      foreign_key: 'job_application_id'

    validates :job_seeker, presence: true
    validates :job, presence: true
    validates :cover_letter, presence: true, length: { minimum: 50 }
    validates :rejection_feedback, allow_nil: true, allow_blank: false,
                                   length: { minimum: 50 }

    scope :ongoing, -> { where rejection_feedback: nil }

    def rejected?
      rejection_feedback.present?
    end

    def status
      return Job::Application.human_attribute_name 'status.rejected' if rejected?

      Job::Application.human_attribute_name 'status.ongoing'
    end
  end
end

app/models/job/application/interview.rb
# frozen_string_literal: true

class Job
  class Application
    class Interview < ActiveRecord::Base
      belongs_to :application, class_name: Job::Application.name,
                               foreign_key: 'job_application_id'
      belongs_to :head_hunter
      has_one :job_seeker, through: :application
      has_one :job, through: :application

      validates :application, presence: true
      validates :head_hunter, presence: true
      validates :address, presence: true
      validates :date, presence: true
      validate :whether_date_is_a_datetime
      validate :whether_its_in_the_future

      default_scope -> { order date: :desc }

      private

      def whether_date_is_a_datetime
        return if date&.is_a? Time

        errors.add :date, :invalid
      end

      def whether_its_in_the_future
        return if date_is_in_the_future?

        errors.add :date, :retroactive
      end

      def date_is_in_the_future?
        date && date > DateTime.now
      end
    end
  end
end

app/models/job/application/offer.rb
# frozen_string_literal: true

class Job
  class Application
    class Offer < ActiveRecord::Base
      belongs_to :application, class_name: Job::Application.name,
                               foreign_key: 'job_application_id'
      belongs_to :head_hunter
      has_one :job_seeker, through: :application
      has_one :job, through: :application

      enum status: { ongoing: 0, accepted: 1, rejected: 2 }

      validates :application, presence: true
      validates :head_hunter, presence: true
      validates :start_date, presence: true, format: { with: ApplicationHelper::DATE_REGEX }
      validate :whether_it_starts_in_the_future
      validates :salary,
                presence: true,
                numericality: { only_integer: true,
                                greater_than_or_equal_to: BRAZILIAN_MINIMUM_WAGE }
      validates :responsabilities, presence: true, length: { minimum: 50 }
      validates :benefits, presence: true, length: { minimum: 50 }

      default_scope -> { order created_at: :desc }

      def reject! feedback = nil
        update_attribute :status, :rejected
        update_attribute :feedback, feedback if feedback
      end

      def reject_with_default_feedback!
        update_attribute :status, :rejected
        update_attribute :feedback, I18n.t('activerecord.attributes.job/application/offer.accepted_another_offer')
      end

      def accept! feedback = nil
        update_attribute :status, :accepted
        update_attribute :feedback, feedback if feedback
      end

      private

      def whether_it_starts_in_the_future
        return if start_date_is_in_the_future?

        errors.add :start_date, :retroactive
      end

      def start_date_is_in_the_future?
        start_date && start_date > Date.today
      end
    end
  end
end

app/controllers/hunter/jobs_controller.rb
# frozen_string_literal: true

module Hunter
  class JobsController < BaseController
    before_action :check_head_hunter, only: %i[show retire]

    def index
      @jobs = current_head_hunter.jobs
    end

    def show
      @applications = @job.ongoing_applications
    end

    def new
      @job = Job.new
    end

    def create
      @job = Job.new job_params
      @job.head_hunter = current_head_hunter
      if @job.save
        flash[:success] = t 'flash.created',
                            resource: t('activerecord.models.job.one')
        redirect_to hunter_job_path @job
      else
        render :new
      end
    end

    def retire
      @job.retire!

      flash[:success] = t 'flash.job_retired'
      redirect_to hunter_job_path @job
    end

    private

    def job_params
      params.require(:job).permit :position, :title, :description, :skills,
                                  :salary_floor, :salary_roof, :location, :expires_on
    end

    def check_head_hunter
      @job = Job.find params[:id] || params[:job_id]
      return if @job.head_hunter == current_head_hunter

      flash[:danger] = t 'flash.unauthorized'
      redirect_to hunter_jobs_path
    end
  end
end

app/controllers/seeker/applications_controller.rb
# frozen_string_literal: true

module Seeker
  class ApplicationsController < BaseController
    before_action :check_active_job, only: %i[new create]
    before_action :check_if_already_applied, only: %i[new create]
    before_action :check_applicant, only: %i[show]

    def index
      @applications = current_job_seeker.applications
    end

    def show
      @offers = @application.offers
    end

    def new
      @application = Job::Application.new
    end

    def create
      @application = build_application

      if @application.save
        flash[:success] = t 'flash.created',
                            resource: t('activerecord.models.job/application.one')
        redirect_to seeker_jobs_path
      else
        render :new
      end
    end

    private

    def build_application
      application = Job::Application.new application_params
      application.job = @job
      application.job_seeker = current_job_seeker
      application
    end

    def application_params
      params.require(:job_application).permit :cover_letter
    end

    def check_active_job
      @job = Job.find params[:job_id]
      return if @job.active?

      flash[:danger] = t 'flash.inactive_job'
      redirect_to seeker_jobs_path
    end

    def check_if_already_applied
      return unless current_job_seeker.already_applied? params[:job_id]

      flash[:danger] = t 'flash.already_applied'
      redirect_to seeker_job_path(@job)
    end

    def check_applicant
      @application = Job::Application.find params[:id]
      return if @application.job_seeker == current_job_seeker

      flash[:danger] = t 'flash.unauthorized'
      redirect_to seeker_applications_path
    end
  end
end

app/controllers/seeker/base_controller.rb
# frozen_string_literal: true

module Seeker
  class BaseController < ApplicationController
    before_action :authenticate_job_seeker!
    before_action :check_profile

    private

    def check_profile
      redirect_to new_seeker_profile_path unless current_job_seeker.profile?
    end
  end
end

app/controllers/seeker/dashboard_controller.rb
# frozen_string_literal: true

module Seeker
  class DashboardController < BaseController
    def index; end
  end
end

app/controllers/seeker/jobs_controller.rb
# frozen_string_literal: true

module Seeker
  class JobsController < BaseController
    before_action :check_active_job, only: %i[show]

    def index
      if params[:search]
        search_jobs
      else
        @jobs = Job.active
      end
    end

    def show; end

    private

    def search_jobs
      @jobs = Job.active.by_title_or_description params[:search]
      return unless @jobs.empty?

      @jobs = Job.active
      flash.now[:info] = t 'flash.job_not_found'
    end

    def check_active_job
      @job = Job.find params[:id]
      return if @job.active?

      flash[:danger] = t 'flash.inactive_job'
      redirect_to seeker_jobs_path
    end
  end
end

app/controllers/seeker/offers_controller.rb
# frozen_string_literal: true

module Seeker
  class OffersController < BaseController
    skip_before_action :verify_authenticity_token, only: %i[accept reject]

    before_action :check_job_seeker, only: %i[show accept reject]
    before_action :check_status, only: %i[accept reject]
    before_action :reject_ongoing_offers, only: %i[accept]

    def index
      @offers = current_job_seeker.offers
    end

    def show; end

    def accept
      @offer.accept! params[:feedback]

      flash[:success] = t 'flash.offer_accepted'
      redirect_to request.referer
    end

    def reject
      @offer.reject! params[:feedback]

      flash[:success] = t 'flash.offer_rejected'
      redirect_to request.referer
    end

    private

    def check_job_seeker
      @offer = Job::Application::Offer.find params[:id] || params[:offer_id]
      return if @offer.job_seeker == current_job_seeker

      flash[:danger] = t 'flash.unauthorized'
      redirect_to seeker_offers_path
    end

    def check_status
      return if @offer.ongoing?

      flash[:danger] = t 'flash.closed_offer'
      redirect_to seeker_offer_path(@offer)
    end

    def reject_ongoing_offers
      @ongoing_offers = current_job_seeker.offers.ongoing
      @rejected_offers = @ongoing_offers.filter { |offer| offer != @offer }
      @rejected_offers.each(&:reject_with_default_feedback!)
    end
  end
end

app/controllers/seeker/profiles_controller.rb
# frozen_string_literal: true

module Seeker
  class ProfilesController < BaseController
    before_action :load_profile, only: %i[show edit update]
    before_action :check_profile, only: %i[new create]

    def show; end

    def new
      flash.clear
      flash.now[:info] = t 'flash.fill_out_profile'
      @profile = JobSeeker::Profile.new
    end

    def create
      @profile = JobSeeker::Profile.new profile_params
      @profile.job_seeker = current_job_seeker

      if @profile.save
        flash[:success] = t 'devise.registrations.signed_up'
        redirect_to seeker_dashboard_path
      else
        render :new
      end
    end

    def edit; end

    def update
      if @profile.update profile_params
        flash[:success] = t 'flash.updated',
                            resource: t('activerecord.models.job_seeker/profile.one')
        redirect_to seeker_show_profile_path
      else
        render :edit
      end
    end

    private

    def profile_params
      params.require(:job_seeker_profile).permit :date_of_birth, :high_school,
                                                 :college, :degrees, :courses,
                                                 :interests, :bio, :avatar,
                                                 :work_experience
    end

    def load_profile
      @profile = current_job_seeker.profile
    end

    def check_profile
      redirect_to seeker_show_profile_path if current_job_seeker.profile?
    end
  end
end

app/controllers/seeker/registrations_controller.rb
# frozen_string_literal: true

module Seeker
  class RegistrationsController < Devise::RegistrationsController
    include Accessible
    skip_before_action :check_user, except: %i[new create]
  end
end

app/controllers/seeker/sessions_controller.rb
# frozen_string_literal: true

module Seeker
  class SessionsController < Devise::SessionsController
    include Accessible
    skip_before_action :check_user, only: :destroy
  end
end

app/views/seeker/jobs/_searchbar.html.erb
<%= form_with url: seeker_jobs_path, local: true, method: :get, 
              class: 'jobs_searchbar' do |f| %>
  <div class="form-row align-items-center my-1">
    <div class="col-auto">
      <%= f.label :search, t('views.jobs.search'), class: 'sr-only' %>
      <%= f.search_field :search, placeholder: t('views.placeholders.search_jobs'), 
                          class: 'form-control mb-2' %>
    </div>

    <div class="col-auto">
      <%= f.submit t('views.actions.search'), class: 'btn btn-outline-info mb-2' %>
    </div>
  </div>
<% end %>

app/views/seeker/jobs/index.html.erb
<main class='row'>
  <div class='col-md-12'>
    <nav class='context_navigation'>
      <%= link_to t('views.navigation.go_back'), :back, class: 'btn btn-outline-secondary' %>
    </nav>

    <header class='header'>
      <h1><%= t('activerecord.models.job.other') %></h1>

      <div class="inline_filter">
        <p><%= t('views.jobs.job_seeker_description') %></p>

        <%= render 'searchbar' %>
      </div>
    </header>

    <section class='contents'>

      <% if @jobs.empty? %>
        <p class="empty_resource"><%= t('views.jobs.empty_resource') %></p>
      <% else %>

      <table class="col index_table">
          <thead class="index_table_head">
            <tr class="index_table_row">
              <th><%= t('activerecord.attributes.job.position') %></th>
              <th><%= t('activerecord.attributes.job.title') %></th>
              <th><%= t('activerecord.attributes.job.expires_on') %></th>
              <th></th>
            </tr>
          </thead>

          <tbody class="index_table_body">
            <% @jobs.each do |job| %>
              <tr class="index_table_row" id="job-<%= job.id %>">
                <td><%= job.position %></td>
                <td><%= job.title %></td>
                <td>
                  <span class="status_dot <%= job.active? ? 'active_dot' : 'inactive_dot' %>"></span>
                  <%= l(job.expires_on) %>
                </td>

                <td><%= link_to t('views.navigation.details'), seeker_job_path(job), id: "details-#{job.id}" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>

    </section>

    <div class='actions mt-4'>
    </div>
  </div>
</main>

app/views/seeker/jobs/show.html.erb
<main class='row'>
  <div class='col-12'>
    <nav class='context_navigation'>
      <%= link_to t('views.navigation.go_back'), seeker_jobs_path, class: 'btn btn-outline-secondary' %>

      <% unless current_job_seeker.already_applied? @job.id  %>
        <%= link_to t('views.navigation.apply'), new_seeker_job_application_path(@job), 
                    class: 'btn btn-primary' %>
      <% end %>
    </nav>

    <header class='header'>
      <h1> <%= "#{@job.position} #{t('views.support.of')} #{@job.title}" %> </h1>

      <p class="indent"> <%= @job.description %> </p>
    </header>

    <section class='contents row'>
      <aside class="col-3">
        <dl class="side_info_box">
          <dt><%= t('activerecord.attributes.job.created_by') %>:</dt>
          <dd><%= @job.head_hunter.resolve_name %> </dd>
          <dt><%= t('activerecord.attributes.head_hunter.email') %>:</dt>
          <dd><%= @job.head_hunter.email %> </dd>
        </dl>
      </aside>

      <dl class="col">
        <dt class="job_status <%= @job.active? ? 'active_job' : 'inactive_job' %>"> 
          <%= @job.active? ? t('activerecord.attributes.job.active') : t('activerecord.attributes.job.inactive') %>
        </dt>
        <dt><%= t('activerecord.attributes.job.skills') %>:</dt>
        <dd> <%= @job.skills %> </dd>
        <dt><%= t('activerecord.attributes.job.salary_range') %>:</dt>
        <dd> <%= number_to_currency(@job.salary_floor) + '-' + number_to_currency(@job.salary_roof) %> </dd>
        <dt><%= t('activerecord.attributes.job.location') %>:</dt>
        <dd> <%= @job.location %> </dd>
        <dt><%= t('activerecord.attributes.job.expires_on') %>:</dt>
        <dd> <%= l(@job.expires_on) %> </dd>
      </dl>
    </section>

    <div class='actions mt-4'>

    </div>
  </div>
</main>