config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :head_hunters, path: 'head_hunter_accounts', controllers: {
    registrations: 'hunter/registrations',
    sessions: 'hunter/sessions'
  }
  devise_for :job_seekers, path: 'job_seeker_accounts', controllers: {
    registrations: 'seeker/registrations',
    sessions: 'seeker/sessions'
  }

  root 'home#index'

  namespace :hunter do
    root 'dashboard#index'
    get '/dashboard', to: 'dashboard#index', as: :dashboard

    resources :jobs, only: %i[index show new create] do
      patch :retire
    end

    resources :applications, only: %i[index show] do
      patch :standout
      get   :rejection
      patch :reject

      resources :offers, only: %i[new create]
    end

    resources :applicants, only: %i[index show] do
      post :comment
    end

    resources :offers, only: %i[index show]
  end

  namespace :seeker do
    root 'dashboard#index'
    get '/dashboard', to: 'dashboard#index', as: :dashboard

    resources :profiles, only: %i[new create]
    get '/profile', to: 'profiles#show', as: :show_profile
    get '/profile/edit', to: 'profiles#edit', as: :edit_profile
    patch '/profile', to: 'profiles#update', as: :update_profile

    resources :jobs, only: %i[index show] do
      resources :applications, only: %i[new create]
    end

    resources :applications, only: %i[index show]
    resources :offers, only: %i[index show] do
      patch :accept
      patch :reject
    end
  end
end

app/models/job/application.rb
# frozen_string_literal: true

class Job
  class Application < ActiveRecord::Base
    belongs_to :job
    belongs_to :job_seeker

    has_one :head_hunter, through: :job

    has_many :offers, dependent: :destroy, class_name: Job::Application::Offer.name,
                      foreign_key: 'job_application_id'

    validates :job_seeker, presence: true
    validates :job, presence: true
    validates :cover_letter, presence: true, length: { minimum: 50 }
    validates :rejection_feedback, allow_nil: true, allow_blank: false,
                                   length: { minimum: 50 }

    scope :ongoing, -> { where rejection_feedback: nil }

    def rejected?
      rejection_feedback.present?
    end

    def status
      return Job::Application.human_attribute_name 'status.rejected' if rejected?

      Job::Application.human_attribute_name 'status.ongoing'
    end
  end
end

app/models/job/application/interview.rb
# frozen_string_literal: true

class Job
  class Application
    class Interview < ActiveRecord::Base
      belongs_to :application, class_name: Job::Application.name,
                               foreign_key: 'job_application_id'
      belongs_to :head_hunter
      has_one :job_seeker, through: :application
      has_one :job, through: :application

      validates :application, presence: true
      validates :head_hunter, presence: true
      validates :address, presence: true
      validates :date, presence: true
      validate :whether_date_is_a_datetime
      validate :whether_its_in_the_future

      default_scope -> { order date: :desc }

      private

      def whether_date_is_a_datetime
        return if date&.is_a? Time

        errors.add :date, :invalid
      end

      def whether_its_in_the_future
        return if date_is_in_the_future?

        errors.add :date, :retroactive
      end

      def date_is_in_the_future?
        date && date > DateTime.now
      end
    end
  end
end

app/models/job/application/offer.rb
# frozen_string_literal: true

class Job
  class Application
    class Offer < ActiveRecord::Base
      belongs_to :application, class_name: Job::Application.name,
                               foreign_key: 'job_application_id'
      belongs_to :head_hunter
      has_one :job_seeker, through: :application
      has_one :job, through: :application

      enum status: { ongoing: 0, accepted: 1, rejected: 2 }

      validates :application, presence: true
      validates :head_hunter, presence: true
      validates :start_date, presence: true, format: { with: ApplicationHelper::DATE_REGEX }
      validate :whether_it_starts_in_the_future
      validates :salary,
                presence: true,
                numericality: { only_integer: true,
                                greater_than_or_equal_to: BRAZILIAN_MINIMUM_WAGE }
      validates :responsabilities, presence: true, length: { minimum: 50 }
      validates :benefits, presence: true, length: { minimum: 50 }

      default_scope -> { order created_at: :desc }

      def reject! feedback = nil
        update_attribute :status, :rejected
        update_attribute :feedback, feedback if feedback
      end

      def reject_with_default_feedback!
        update_attribute :status, :rejected
        update_attribute :feedback, I18n.t('activerecord.attributes.job/application/offer.accepted_another_offer')
      end

      def accept! feedback = nil
        update_attribute :status, :accepted
        update_attribute :feedback, feedback if feedback
      end

      private

      def whether_it_starts_in_the_future
        return if start_date_is_in_the_future?

        errors.add :start_date, :retroactive
      end

      def start_date_is_in_the_future?
        start_date && start_date > Date.today
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def after_sign_in_path_for resource
    return hunter_dashboard_path if resource.class.name == 'HeadHunter'
    return seeker_dashboard_path if resource.class.name == 'JobSeeker'
  end

  def after_sign_out_path_for _resource
    root_path
  end

  protected

  def devise_parameter_sanitizer
    if resource_class == HeadHunter
      HeadHunter::ParameterSanitizer.new HeadHunter, :head_hunter, params
    else
      JobSeeker::ParameterSanitizer.new JobSeeker, :job_seeker, params
    end
  end
end

app/controllers/hunter/applicants_controller.rb
# frozen_string_literal: true

module Hunter
  class ApplicantsController < BaseController
    before_action :check_profile, only: %i[show comment]

    def index
      @applicants = current_head_hunter.applicants.uniq
    end

    def show
      @comment = JobSeeker::Profile::Comment.new
    end

    def comment
      @comment = build_comment

      if @comment.save
        flash[:success] = t 'flash.created',
                            resource: t('activerecord.models.job_seeker/profile/comment.one')
        redirect_to request.referer
      else
        render :show
      end
    end

    private

    def comment_params
      params.require(:job_seeker_profile_comment).permit :content
    end

    def build_comment
      comment = JobSeeker::Profile::Comment.new comment_params
      comment.profile = @profile
      comment.head_hunter = current_head_hunter
      comment
    end

    def check_profile
      @applicant = JobSeeker.find params[:id] || params[:applicant_id]
      @profile = @applicant.profile
      return if @profile

      flash[:danger] = t 'flash.profile_not_found'
      redirect_to hunter_applicants_path
    end
  end
end

app/controllers/hunter/applications_controller.rb
# frozen_string_literal: true

module Hunter
  class ApplicationsController < BaseController
    before_action :check_head_hunter, except: %i[index]

    def index
      @applications = current_head_hunter.applications.ongoing
    end

    def show
      @applicant = @application.job_seeker
    end

    def standout
      @application.update standout: @application.standout.!
      redirect_to request.referer
    end

    def rejection; end

    def reject
      if @application.update rejection_params
        flash[:success] = t 'flash.application_rejected'
        redirect_to hunter_applications_path
      else
        render :rejection
      end
    end

    private

    def rejection_params
      params.require(:job_application).permit :rejection_feedback
    end

    def check_head_hunter
      @application = Job::Application.find params[:id] || params[:application_id]
      return if @application.head_hunter == current_head_hunter

      flash[:danger] = t 'flash.unauthorized'
      redirect_to hunter_applications_path
    end
  end
end

app/controllers/hunter/base_controller.rb
# frozen_string_literal: true

module Hunter
  class BaseController < ApplicationController
    before_action :authenticate_head_hunter!
  end
end

app/controllers/hunter/dashboard_controller.rb
# frozen_string_literal: true

module Hunter
  class DashboardController < BaseController
    def index; end
  end
end

app/controllers/hunter/jobs_controller.rb
# frozen_string_literal: true

module Hunter
  class JobsController < BaseController
    before_action :check_head_hunter, only: %i[show retire]

    def index
      @jobs = current_head_hunter.jobs
    end

    def show
      @applications = @job.ongoing_applications
    end

    def new
      @job = Job.new
    end

    def create
      @job = Job.new job_params
      @job.head_hunter = current_head_hunter
      if @job.save
        flash[:success] = t 'flash.created',
                            resource: t('activerecord.models.job.one')
        redirect_to hunter_job_path @job
      else
        render :new
      end
    end

    def retire
      @job.retire!

      flash[:success] = t 'flash.job_retired'
      redirect_to hunter_job_path @job
    end

    private

    def job_params
      params.require(:job).permit :position, :title, :description, :skills,
                                  :salary_floor, :salary_roof, :location, :expires_on
    end

    def check_head_hunter
      @job = Job.find params[:id] || params[:job_id]
      return if @job.head_hunter == current_head_hunter

      flash[:danger] = t 'flash.unauthorized'
      redirect_to hunter_jobs_path
    end
  end
end

app/controllers/hunter/offers_controller.rb
# frozen_string_literal: true

module Hunter
  class OffersController < BaseController
    before_action :resolve_job, :check_head_hunter, except: :index

    def index
      @offers = current_head_hunter.offers
    end

    def show; end

    def new
      @offer = Job::Application::Offer.new
    end

    def create
      @offer = build_offer

      if @offer.save
        flash[:success] = t 'flash.created',
                            resource: t('activerecord.models.job/application/offer.one')
        redirect_to hunter_offer_path @offer
      else
        render :new
      end
    end

    private

    def offer_params
      params.require(:job_application_offer).permit :start_date, :salary, :responsabilities,
                                                    :benefits, :expectations, :bonus
    end

    def build_offer
      offer = Job::Application::Offer.new offer_params
      offer.application = @application
      offer.head_hunter = current_head_hunter
      offer
    end

    def resolve_job
      if params[:application_id]
        @application = Job::Application.find params[:application_id]
        @job = @application.job
      else
        @offer = Job::Application::Offer.find params[:id]
        @job = @offer.job
      end
    end

    def check_head_hunter
      return if @job.head_hunter == current_head_hunter

      flash[:danger] = t 'flash.unauthorized'
      redirect_to hunter_offers_path
    end
  end
end

app/controllers/hunter/registrations_controller.rb
# frozen_string_literal: true

module Hunter
  class RegistrationsController < Devise::RegistrationsController
    include Accessible
    skip_before_action :check_user, except: %i[new create]
  end
end

app/controllers/hunter/sessions_controller.rb
# frozen_string_literal: true

module Hunter
  class SessionsController < Devise::SessionsController
    include Accessible
    skip_before_action :check_user, only: :destroy
  end
end

app/controllers/seeker/applications_controller.rb
# frozen_string_literal: true

module Seeker
  class ApplicationsController < BaseController
    before_action :check_active_job, only: %i[new create]
    before_action :check_if_already_applied, only: %i[new create]
    before_action :check_applicant, only: %i[show]

    def index
      @applications = current_job_seeker.applications
    end

    def show
      @offers = @application.offers
    end

    def new
      @application = Job::Application.new
    end

    def create
      @application = build_application

      if @application.save
        flash[:success] = t 'flash.created',
                            resource: t('activerecord.models.job/application.one')
        redirect_to seeker_jobs_path
      else
        render :new
      end
    end

    private

    def build_application
      application = Job::Application.new application_params
      application.job = @job
      application.job_seeker = current_job_seeker
      application
    end

    def application_params
      params.require(:job_application).permit :cover_letter
    end

    def check_active_job
      @job = Job.find params[:job_id]
      return if @job.active?

      flash[:danger] = t 'flash.inactive_job'
      redirect_to seeker_jobs_path
    end

    def check_if_already_applied
      return unless current_job_seeker.already_applied? params[:job_id]

      flash[:danger] = t 'flash.already_applied'
      redirect_to seeker_job_path(@job)
    end

    def check_applicant
      @application = Job::Application.find params[:id]
      return if @application.job_seeker == current_job_seeker

      flash[:danger] = t 'flash.unauthorized'
      redirect_to seeker_applications_path
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  DATE_REGEX = /\d{4}-\d{2}-\d{2}/.freeze
end

app/views/hunter/applications/_offers.html.erb
<section class='contents'>

  <% if @application.offers.empty? %>
    <p class="empty_resource"><%= t('views.jobs/applications/offers.empty_resource') %></p>
  <% else %>
    <dl class="offer_feed col-12">
      <h2 class="offer_feed_title">
        <%= t('activerecord.models.job/application/offer.other') %>
      </h2>

      <% @application.offers.each do |offer| %>
        <div id="offer-<%= offer.id %>" class="offer <%= offer.status %>_offer">
          <dt class="offer_head">
            <span class="offer_creator">
              <%= image_tag url_for(offer.head_hunter.avatar),
                alt: offer.head_hunter.resolve_name,
                class: 'offerer_avatar' %>

              <span class="offerer_name">
                <%= offer.head_hunter.resolve_name %>
              </span>
            </span>

            <span class="offer_timestamp">
              <%= l(offer.created_at, format: :long) %>
            </span>
          </dt>

          <div class="offer_overview">
            <span>
              <dt><%= t('activerecord.attributes.job/application/offer.status') %>:</dt>
              <dd> <%= t("activerecord.attributes.job/application/offer/status.#{offer.status}") %> </dd>
            </span>

            <span>
              <dt><%= t('activerecord.attributes.job/application/offer.start_date') %>:</dt>
              <dd> <%= l(offer.start_date) %> </dd>
            </span>

            <span>
              <dt><%= t('activerecord.attributes.job/application/offer.salary') %>:</dt>
              <dd> <%= number_to_currency(offer.salary) %> </dd>
            </span>
          </div>

          <dt><%= t('activerecord.attributes.job/application/offer.responsabilities') %>:</dt>
          <dd class="indent"> <%= offer.responsabilities %> </dd>

          <dt><%= t('activerecord.attributes.job/application/offer.benefits') %>:</dt>
          <dd class="indent"> <%= offer.benefits %> </dd>

          <% if offer.expectations.present? %>
            <dt><%= t('activerecord.attributes.job/application/offer.expectations') %>:</dt>
            <dd class="indent"> <%= offer.expectations %> </dd>
          <% end %>

          <% if offer.bonus.present? %>
            <dt><%= t('activerecord.attributes.job/application/offer.bonus') %>:</dt>
            <dd class="indent"> <%= offer.bonus %> </dd>
          <% end %>

          <% if offer.feedback.present? %>
            <dt><%= t('activerecord.attributes.job/application/offer.feedback') %>:</dt>
            <dd class="indent"> <%= offer.feedback %> </dd>
          <% end %>

        </div>
      <% end %>
    </dl>
  <% end %>

</section>

app/views/hunter/applications/_rejection_form.html.erb
<%= form_with model: @application, url: yield(:resource_path), local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class='form-group'>
    <%= f.label :rejection_feedback %>
    <%= f.text_area :rejection_feedback, required: true, minlength: 50, class: 'form-control' %>
  </div>

  <%= f.submit t('views.actions.send'), class: 'btn btn-primary' %>
<% end %>

app/views/hunter/applications/index.html.erb
<main class='row'>
  <div class='col-md-12'>
    <nav class='context_navigation'>
      <%= link_to t('views.navigation.go_back'), :back, class: 'btn btn-outline-secondary' %>
    </nav>

    <header class='header'>
      <h1><%= t('activerecord.models.job/application.other') %></h1>

      <p><%= t('views.jobs/applications.description') %></p>
    </header>

    <section class='contents'>

      <% if @applications.empty? %>
        <p class="empty_resource"><%= t('views.jobs/applications.empty_resource') %></p>
      <% else %>

      <table class="col index_table">
          <thead class="index_table_head">
            <tr class="index_table_row">
              <th></th>
              <th><%= t('activerecord.models.job.one') %></th>
              <th><%= t('activerecord.models.job_seeker.one') %></th>
              <th></th>
            </tr>
          </thead>

          <tbody class="index_table_body">
            <% @applications.each do |application| %>
              <tr class="index_table_row" id="application-<%= application.id %>">
                <td> <%= render 'hunter/shared/standout_form', application: application, small: true %> </td>
                <td> <%= link_to application.job.title, hunter_job_path(application.job) %> </td>
                <td> <%= link_to application.job_seeker.resolve_name, hunter_applicant_path(application.job_seeker) %> </td>

                <td><%= link_to t('views.navigation.details'), hunter_application_path(application), id: "details-#{application.id}" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>

    </section>

    <div class='actions mt-4'>
    </div>
  </div>
</main>

app/views/hunter/applications/rejection.html.erb
<% provide(:resource_path, hunter_application_reject_path) %>

<main class='row'>
  <div class='col-md-12'>
    <nav class='context_navigation'>
      <%= link_to t('views.navigation.go_back'), hunter_application_path(@application), 
                  class: 'btn btn-outline-secondary' %>
    </nav>

    <header class='header'>
      <h1> <%= t 'views.head_hunters.applications.rejection.title' %> </h1>

      <p> <%=  t 'views.head_hunters.applications.rejection.description' %> </p>
    </header>

    <section class='contents'>
      <%= render 'rejection_form' %>
    </section>

    <div class='actions mt-4'>
    </div>
  </div>
</main>

app/views/hunter/applications/show.html.erb
<main class='row'>
  <div class='col-md-12'>
    <nav class='context_navigation'>
      <%= link_to t('views.navigation.go_back'), hunter_applications_path, class: 'btn btn-outline-secondary' %>

      <span>
        <%= link_to t('views.navigation.offer'), new_hunter_application_offer_path(@application),
                    class: 'btn btn-primary' %>
        <%= link_to t('views.navigation.reject'), hunter_application_rejection_path(@application),
                    class: 'btn btn-danger' %>
      </span>
    </nav>

    <header class='header'>
      <div class="applicant_title">
        <h1> <%= @applicant.resolve_name %> </h1>

        <%= render 'hunter/shared/standout_form', application: @application, small: false %>
      </div>

      <p class="indent"> <%= @applicant.profile.bio %> </p>
    </header>

    <section class='contents row'>
      <dl class="col">
        <dt><%= t('activerecord.attributes.job/application.cover_letter') %>:</dt>
        <dd class="indent"> <%= @application.cover_letter %> </dd>
      </dl>
    </section>

    <%= render 'offers' %>

  </div>
</main>