config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :head_hunters, path: 'head_hunter_accounts', controllers: {
    registrations: 'hunter/registrations',
    sessions: 'hunter/sessions'
  }
  devise_for :job_seekers, path: 'job_seeker_accounts', controllers: {
    registrations: 'seeker/registrations',
    sessions: 'seeker/sessions'
  }

  root 'home#index'

  namespace :hunter do
    root 'dashboard#index'
    get '/dashboard', to: 'dashboard#index', as: :dashboard

    resources :jobs, only: %i[index show new create] do
      patch :retire
    end

    resources :applications, only: %i[index show] do
      patch :standout
      get   :rejection
      patch :reject

      resources :offers, only: %i[new create]
    end

    resources :applicants, only: %i[index show] do
      post :comment
    end

    resources :offers, only: %i[index show]
  end

  namespace :seeker do
    root 'dashboard#index'
    get '/dashboard', to: 'dashboard#index', as: :dashboard

    resources :profiles, only: %i[new create]
    get '/profile', to: 'profiles#show', as: :show_profile
    get '/profile/edit', to: 'profiles#edit', as: :edit_profile
    patch '/profile', to: 'profiles#update', as: :update_profile

    resources :jobs, only: %i[index show] do
      resources :applications, only: %i[new create]
    end

    resources :applications, only: %i[index show]
    resources :offers, only: %i[index show] do
      patch :accept
      patch :reject
    end
  end
end

app/models/job.rb
# frozen_string_literal: true

class Job < ApplicationRecord
  BRAZILIAN_MINIMUM_WAGE = 1039

  belongs_to :head_hunter
  has_many :applications, dependent: :destroy, class_name: Job::Application.name
  has_many :applicants, through: :applications, source: :job_seeker

  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 50 }
  validates :skills, presence: true
  validates :salary_floor,
            numericality: { only_integer: true,
                            greater_than_or_equal_to: BRAZILIAN_MINIMUM_WAGE,
                            less_than: 50_000 }, presence: true
  validates :salary_roof, numericality: { only_integer: true, less_than: 50_200 },
                          presence: true
  validate :whether_the_salary_range_is_reasonable
  validates :position, presence: true
  validates :location, presence: true
  validates :retired, inclusion: { in: [true, false] }
  validates :expires_on, presence: true, format: { with: ApplicationHelper::DATE_REGEX }
  validate :whether_it_expires_in_a_month
  validates :head_hunter, presence: true

  before_save :titleize_attributes

  default_scope -> { order expires_on: :desc }
  scope :created_by, ->(head_hunter) { where head_hunter: head_hunter }
  scope :active, -> { where "retired = FALSE AND expires_on > DATE('now')" }
  scope :by_title_or_description, lambda { |search|
                                    where 'title like ? OR description like ?',
                                          "%#{search}%", "%#{search}%"
                                  }

  def expired?
    expires_on < Date.today
  end

  def active?
    return false if expired?

    !retired
  end

  def retire!
    update_attribute :retired, true
  end

  def minimum_wage
    BRAZILIAN_MINIMUM_WAGE
  end

  def ongoing_applications
    applications.where rejection_feedback: nil
  end

  private

  def whether_the_salary_range_is_reasonable
    return if salary_floor.nil?
    return if salary_roof && salary_roof >= salary_floor + 200

    errors.add :salary_roof, :greater_than_or_equal_to, count: salary_floor + 200
  end

  def whether_it_expires_in_a_month
    return if expires_on_is_at_least_one_month_away?

    errors.add :expires_on, :before_one_month
  end

  def expires_on_is_at_least_one_month_away?
    expires_on && 1.month.from_now <= expires_on
  end

  def titleize_attributes
    self.title = title.titleize
    self.skills = skills.titleize
    self.position = position.titleize
    self.location = location.titleize
  end
end

app/models/job/application.rb
# frozen_string_literal: true

class Job
  class Application < ActiveRecord::Base
    belongs_to :job
    belongs_to :job_seeker

    has_one :head_hunter, through: :job

    has_many :offers, dependent: :destroy, class_name: Job::Application::Offer.name,
                      foreign_key: 'job_application_id'

    validates :job_seeker, presence: true
    validates :job, presence: true
    validates :cover_letter, presence: true, length: { minimum: 50 }
    validates :rejection_feedback, allow_nil: true, allow_blank: false,
                                   length: { minimum: 50 }

    scope :ongoing, -> { where rejection_feedback: nil }

    def rejected?
      rejection_feedback.present?
    end

    def status
      return Job::Application.human_attribute_name 'status.rejected' if rejected?

      Job::Application.human_attribute_name 'status.ongoing'
    end
  end
end

app/models/job/application/interview.rb
# frozen_string_literal: true

class Job
  class Application
    class Interview < ActiveRecord::Base
      belongs_to :application, class_name: Job::Application.name,
                               foreign_key: 'job_application_id'
      belongs_to :head_hunter
      has_one :job_seeker, through: :application
      has_one :job, through: :application

      validates :application, presence: true
      validates :head_hunter, presence: true
      validates :address, presence: true
      validates :date, presence: true
      validate :whether_date_is_a_datetime
      validate :whether_its_in_the_future

      default_scope -> { order date: :desc }

      private

      def whether_date_is_a_datetime
        return if date&.is_a? Time

        errors.add :date, :invalid
      end

      def whether_its_in_the_future
        return if date_is_in_the_future?

        errors.add :date, :retroactive
      end

      def date_is_in_the_future?
        date && date > DateTime.now
      end
    end
  end
end

app/models/job/application/offer.rb
# frozen_string_literal: true

class Job
  class Application
    class Offer < ActiveRecord::Base
      belongs_to :application, class_name: Job::Application.name,
                               foreign_key: 'job_application_id'
      belongs_to :head_hunter
      has_one :job_seeker, through: :application
      has_one :job, through: :application

      enum status: { ongoing: 0, accepted: 1, rejected: 2 }

      validates :application, presence: true
      validates :head_hunter, presence: true
      validates :start_date, presence: true, format: { with: ApplicationHelper::DATE_REGEX }
      validate :whether_it_starts_in_the_future
      validates :salary,
                presence: true,
                numericality: { only_integer: true,
                                greater_than_or_equal_to: BRAZILIAN_MINIMUM_WAGE }
      validates :responsabilities, presence: true, length: { minimum: 50 }
      validates :benefits, presence: true, length: { minimum: 50 }

      default_scope -> { order created_at: :desc }

      def reject! feedback = nil
        update_attribute :status, :rejected
        update_attribute :feedback, feedback if feedback
      end

      def reject_with_default_feedback!
        update_attribute :status, :rejected
        update_attribute :feedback, I18n.t('activerecord.attributes.job/application/offer.accepted_another_offer')
      end

      def accept! feedback = nil
        update_attribute :status, :accepted
        update_attribute :feedback, feedback if feedback
      end

      private

      def whether_it_starts_in_the_future
        return if start_date_is_in_the_future?

        errors.add :start_date, :retroactive
      end

      def start_date_is_in_the_future?
        start_date && start_date > Date.today
      end
    end
  end
end

app/controllers/hunter/applicants_controller.rb
# frozen_string_literal: true

module Hunter
  class ApplicantsController < BaseController
    before_action :check_profile, only: %i[show comment]

    def index
      @applicants = current_head_hunter.applicants.uniq
    end

    def show
      @comment = JobSeeker::Profile::Comment.new
    end

    def comment
      @comment = build_comment

      if @comment.save
        flash[:success] = t 'flash.created',
                            resource: t('activerecord.models.job_seeker/profile/comment.one')
        redirect_to request.referer
      else
        render :show
      end
    end

    private

    def comment_params
      params.require(:job_seeker_profile_comment).permit :content
    end

    def build_comment
      comment = JobSeeker::Profile::Comment.new comment_params
      comment.profile = @profile
      comment.head_hunter = current_head_hunter
      comment
    end

    def check_profile
      @applicant = JobSeeker.find params[:id] || params[:applicant_id]
      @profile = @applicant.profile
      return if @profile

      flash[:danger] = t 'flash.profile_not_found'
      redirect_to hunter_applicants_path
    end
  end
end

app/controllers/hunter/applications_controller.rb
# frozen_string_literal: true

module Hunter
  class ApplicationsController < BaseController
    before_action :check_head_hunter, except: %i[index]

    def index
      @applications = current_head_hunter.applications.ongoing
    end

    def show
      @applicant = @application.job_seeker
    end

    def standout
      @application.update standout: @application.standout.!
      redirect_to request.referer
    end

    def rejection; end

    def reject
      if @application.update rejection_params
        flash[:success] = t 'flash.application_rejected'
        redirect_to hunter_applications_path
      else
        render :rejection
      end
    end

    private

    def rejection_params
      params.require(:job_application).permit :rejection_feedback
    end

    def check_head_hunter
      @application = Job::Application.find params[:id] || params[:application_id]
      return if @application.head_hunter == current_head_hunter

      flash[:danger] = t 'flash.unauthorized'
      redirect_to hunter_applications_path
    end
  end
end

app/controllers/hunter/base_controller.rb
# frozen_string_literal: true

module Hunter
  class BaseController < ApplicationController
    before_action :authenticate_head_hunter!
  end
end

app/controllers/hunter/dashboard_controller.rb
# frozen_string_literal: true

module Hunter
  class DashboardController < BaseController
    def index; end
  end
end

app/controllers/hunter/jobs_controller.rb
# frozen_string_literal: true

module Hunter
  class JobsController < BaseController
    before_action :check_head_hunter, only: %i[show retire]

    def index
      @jobs = current_head_hunter.jobs
    end

    def show
      @applications = @job.ongoing_applications
    end

    def new
      @job = Job.new
    end

    def create
      @job = Job.new job_params
      @job.head_hunter = current_head_hunter
      if @job.save
        flash[:success] = t 'flash.created',
                            resource: t('activerecord.models.job.one')
        redirect_to hunter_job_path @job
      else
        render :new
      end
    end

    def retire
      @job.retire!

      flash[:success] = t 'flash.job_retired'
      redirect_to hunter_job_path @job
    end

    private

    def job_params
      params.require(:job).permit :position, :title, :description, :skills,
                                  :salary_floor, :salary_roof, :location, :expires_on
    end

    def check_head_hunter
      @job = Job.find params[:id] || params[:job_id]
      return if @job.head_hunter == current_head_hunter

      flash[:danger] = t 'flash.unauthorized'
      redirect_to hunter_jobs_path
    end
  end
end

app/controllers/hunter/offers_controller.rb
# frozen_string_literal: true

module Hunter
  class OffersController < BaseController
    before_action :resolve_job, :check_head_hunter, except: :index

    def index
      @offers = current_head_hunter.offers
    end

    def show; end

    def new
      @offer = Job::Application::Offer.new
    end

    def create
      @offer = build_offer

      if @offer.save
        flash[:success] = t 'flash.created',
                            resource: t('activerecord.models.job/application/offer.one')
        redirect_to hunter_offer_path @offer
      else
        render :new
      end
    end

    private

    def offer_params
      params.require(:job_application_offer).permit :start_date, :salary, :responsabilities,
                                                    :benefits, :expectations, :bonus
    end

    def build_offer
      offer = Job::Application::Offer.new offer_params
      offer.application = @application
      offer.head_hunter = current_head_hunter
      offer
    end

    def resolve_job
      if params[:application_id]
        @application = Job::Application.find params[:application_id]
        @job = @application.job
      else
        @offer = Job::Application::Offer.find params[:id]
        @job = @offer.job
      end
    end

    def check_head_hunter
      return if @job.head_hunter == current_head_hunter

      flash[:danger] = t 'flash.unauthorized'
      redirect_to hunter_offers_path
    end
  end
end

app/controllers/hunter/registrations_controller.rb
# frozen_string_literal: true

module Hunter
  class RegistrationsController < Devise::RegistrationsController
    include Accessible
    skip_before_action :check_user, except: %i[new create]
  end
end

app/controllers/hunter/sessions_controller.rb
# frozen_string_literal: true

module Hunter
  class SessionsController < Devise::SessionsController
    include Accessible
    skip_before_action :check_user, only: :destroy
  end
end

app/controllers/seeker/jobs_controller.rb
# frozen_string_literal: true

module Seeker
  class JobsController < BaseController
    before_action :check_active_job, only: %i[show]

    def index
      if params[:search]
        search_jobs
      else
        @jobs = Job.active
      end
    end

    def show; end

    private

    def search_jobs
      @jobs = Job.active.by_title_or_description params[:search]
      return unless @jobs.empty?

      @jobs = Job.active
      flash.now[:info] = t 'flash.job_not_found'
    end

    def check_active_job
      @job = Job.find params[:id]
      return if @job.active?

      flash[:danger] = t 'flash.inactive_job'
      redirect_to seeker_jobs_path
    end
  end
end

app/views/hunter/jobs/_form.html.erb
<%= form_with model: @job, url: yield(:resource_path), local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class='form-group'>
    <%= f.label :position %>
    <%= f.text_field :position, required: true, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :title %>
    <%= f.text_field :title, required: true, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :description %>
    <%= f.text_area :description, required: true, minlength: 50, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :expires_on %>
    <%= f.date_field :expires_on, value: 1.month.from_now, min: 1.month.from_now, 
                     required: true, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :salary_floor %>
    <%= f.number_field :salary_floor, required: true, min: @job.minimum_wage,
                        class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :salary_roof %>
    <%= f.number_field :salary_roof, required: true, min: @job.minimum_wage + 200,
                        class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :skills %>
    <%= f.text_field :skills, required: true, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :location %>
    <%= f.text_field :location, required: true, class: 'form-control' %>
  </div>

  <%= f.submit t('views.actions.send'), class: 'btn btn-primary' %>
<% end %>

app/views/hunter/jobs/_standout_form.html.erb
<%= form_with url: hunter_application_standout_path(application),
              html: { method: :patch }, local: true, class: 'standout_form' do |f| %>
  <%= f.label :standout, t('activerecord.attributes.job/application.standout'), class: 'sr-only' %>

  <button type="submit" syle="width: 20px;">
    <i class="fas fa-thumbtack <%= application.standout? ? 'small_active_standout' : 'small_inactive_standout' %>"></i>
  </button>
<% end %>

app/views/hunter/jobs/index.html.erb
<main class='row'>
  <div class='col-md-12'>
    <nav class='context_navigation'>
      <%= link_to t('views.navigation.go_back'), :back, class: 'btn btn-outline-secondary' %>
      <%= link_to t('views.navigation.new'), new_hunter_job_path, class: 'btn btn-primary' %>
    </nav>

    <header class='header'>
      <h1><%= t('activerecord.models.job.other') %></h1>

      <p><%= t('views.jobs.description') %></p>
    </header>

    <section class='contents'>

      <% if @jobs.empty? %>
        <p class="empty_resource"><%= t('views.jobs.empty_resource') %></p>
      <% else %>

      <table class="col index_table">
          <thead class="index_table_head">
            <tr class="index_table_row">
              <th><%= t('activerecord.attributes.job.position') %></th>
              <th><%= t('activerecord.attributes.job.title') %></th>
              <th><%= t('activerecord.attributes.job.expires_on') %></th>
              <th></th>
            </tr>
          </thead>

          <tbody class="index_table_body">
            <% @jobs.each do |job| %>
              <tr class="index_table_row" id="job-<%= job.id %>">
                <td><%= job.position %></td>
                <td><%= job.title %></td>
                <td>
                  <span class="status_dot <%= job.active? ? 'active_dot' : 'inactive_dot' %>"></span>
                  <%= l(job.expires_on) %>
                </td>

                <td><%= link_to t('views.navigation.details'), hunter_job_path(job), id: "details-#{job.id}" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>

    </section>

    <div class='actions mt-4'>
    </div>
  </div>
</main>

app/views/hunter/jobs/new.html.erb
<% provide(:resource_path, hunter_jobs_path) %>

<main class='row'>
  <div class='col-md-12'>
    <nav>
      <%= link_to t('views.navigation.go_back'), hunter_jobs_path, class: 'btn btn-outline-secondary' %>
    </nav>

    <header class='header'>
      <h1><%= t('views.jobs.create') %></h1>
    </header>

    <section class='contents'>
      <%= render 'form' %>
    </section>

  </div>
</main>

app/views/hunter/jobs/show.html.erb
<main class='row'>
  <div class='col-12'>
    <nav class='context_navigation'>
      <%= link_to t('views.navigation.go_back'), hunter_jobs_path, class: 'btn btn-outline-secondary' %>

      <%= link_to t('views.actions.retire'), hunter_job_retire_path(@job),
                  data: { confirm: t('views.messages.retire_job') },
                  method: :patch, class: 'btn btn-danger' %>
    </nav>

    <header class='header'>
      <h1> <%= "#{@job.position} #{t('views.support.of')} #{@job.title}" %> </h1>

      <p class="indent"> <%= @job.description %> </p>
    </header>

    <section class='contents row'>

      <aside class="col-3">
        <% if @job.head_hunter.avatar.attached? %>
          <%= image_tag url_for(@job.head_hunter.avatar),
                      alt: @job.head_hunter.resolve_name,
                      class: 'profile_avatar center' %>
        <% else %>
          <%= image_tag 'avatar_placeholder.png',
                      alt: 'User avatar placeholder',
                      class: 'profile_avatar' %>
        <% end %>

        <dl class="side_info_box">
          <dt><%= t('activerecord.attributes.job.created_by') %>:</dt>
          <dd><%= @job.head_hunter.resolve_name %> </dd>
          <dt><%= t('activerecord.attributes.head_hunter.email') %>:</dt>
          <dd><%= @job.head_hunter.email %> </dd>
        </dl>
      </aside>

      <dl class="col-5">
        <dt class="job_status <%= @job.active? ? 'active_job' : 'inactive_job' %>"> 
          <%= @job.active? ? t('activerecord.attributes.job.active') : t('activerecord.attributes.job.inactive') %>
        </dt>
        <dt><%= t('activerecord.attributes.job.skills') %>:</dt>
        <dd> <%= @job.skills %> </dd>
        <dt><%= t('activerecord.attributes.job.salary_range') %>:</dt>
        <dd> <%= number_to_currency(@job.salary_floor) + '-' + number_to_currency(@job.salary_roof) %> </dd>
        <dt><%= t('activerecord.attributes.job.location') %>:</dt>
        <dd> <%= @job.location %> </dd>
        <dt><%= t('activerecord.attributes.job.expires_on') %>:</dt>
        <dd> <%= l(@job.expires_on) %> </dd>
      </dl>

      <aside class="col-4">
        <% if @job.applicants.empty? %>
          <p class="empty_resource"><%= t('views.job_seekers/applications.empty_resource') %></p>
        <% else %>
          <dl class="side_info_box">
            <h2><%= t('activerecord.models.job/application.other') %></h2>
            <% @applications.each do |application| %>
              <dd id="application-<%= application.id %>" class="application_container">
                  <span class="applicant_container">
                    <%= render 'hunter/shared/standout_form', application: application, small: true %>

                    <%= link_to application.job_seeker.resolve_name,
                                hunter_applicant_path(application.job_seeker), 
                                id: "profile-#{application.job_seeker.id}",
                                class: 'application_link' %>
                  </span>

                  <%= link_to t('views.navigation.letter'),
                              hunter_application_path(application),
                              class: 'application_link' %>
              </dd>
            <% end %>
          </dl>
        <% end %>
      </aside>

    </section>

    <div class='actions mt-4'>

    </div>
  </div>
</main>