config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :head_hunters, path: 'head_hunter_accounts', controllers: {
    registrations: 'hunter/registrations',
    sessions: 'hunter/sessions'
  }
  devise_for :job_seekers, path: 'job_seeker_accounts', controllers: {
    registrations: 'seeker/registrations',
    sessions: 'seeker/sessions'
  }

  root 'home#index'

  namespace :hunter do
    root 'dashboard#index'
    get '/dashboard', to: 'dashboard#index', as: :dashboard

    resources :jobs, only: %i[index show new create] do
      patch :retire
    end

    resources :applications, only: %i[index show] do
      patch :standout
      get   :rejection
      patch :reject

      resources :offers, only: %i[new create]
    end

    resources :applicants, only: %i[index show] do
      post :comment
    end

    resources :offers, only: %i[index show]
  end

  namespace :seeker do
    root 'dashboard#index'
    get '/dashboard', to: 'dashboard#index', as: :dashboard

    resources :profiles, only: %i[new create]
    get '/profile', to: 'profiles#show', as: :show_profile
    get '/profile/edit', to: 'profiles#edit', as: :edit_profile
    patch '/profile', to: 'profiles#update', as: :update_profile

    resources :jobs, only: %i[index show] do
      resources :applications, only: %i[new create]
    end

    resources :applications, only: %i[index show]
    resources :offers, only: %i[index show] do
      patch :accept
      patch :reject
    end
  end
end

app/models/job/application.rb
# frozen_string_literal: true

class Job
  class Application < ActiveRecord::Base
    belongs_to :job
    belongs_to :job_seeker

    has_one :head_hunter, through: :job

    has_many :offers, dependent: :destroy, class_name: Job::Application::Offer.name,
                      foreign_key: 'job_application_id'

    validates :job_seeker, presence: true
    validates :job, presence: true
    validates :cover_letter, presence: true, length: { minimum: 50 }
    validates :rejection_feedback, allow_nil: true, allow_blank: false,
                                   length: { minimum: 50 }

    scope :ongoing, -> { where rejection_feedback: nil }

    def rejected?
      rejection_feedback.present?
    end

    def status
      return Job::Application.human_attribute_name 'status.rejected' if rejected?

      Job::Application.human_attribute_name 'status.ongoing'
    end
  end
end

app/models/job/application/interview.rb
# frozen_string_literal: true

class Job
  class Application
    class Interview < ActiveRecord::Base
      belongs_to :application, class_name: Job::Application.name,
                               foreign_key: 'job_application_id'
      belongs_to :head_hunter
      has_one :job_seeker, through: :application
      has_one :job, through: :application

      validates :application, presence: true
      validates :head_hunter, presence: true
      validates :address, presence: true
      validates :date, presence: true
      validate :whether_date_is_a_datetime
      validate :whether_its_in_the_future

      default_scope -> { order date: :desc }

      private

      def whether_date_is_a_datetime
        return if date&.is_a? Time

        errors.add :date, :invalid
      end

      def whether_its_in_the_future
        return if date_is_in_the_future?

        errors.add :date, :retroactive
      end

      def date_is_in_the_future?
        date && date > DateTime.now
      end
    end
  end
end

app/models/job/application/offer.rb
# frozen_string_literal: true

class Job
  class Application
    class Offer < ActiveRecord::Base
      belongs_to :application, class_name: Job::Application.name,
                               foreign_key: 'job_application_id'
      belongs_to :head_hunter
      has_one :job_seeker, through: :application
      has_one :job, through: :application

      enum status: { ongoing: 0, accepted: 1, rejected: 2 }

      validates :application, presence: true
      validates :head_hunter, presence: true
      validates :start_date, presence: true, format: { with: ApplicationHelper::DATE_REGEX }
      validate :whether_it_starts_in_the_future
      validates :salary,
                presence: true,
                numericality: { only_integer: true,
                                greater_than_or_equal_to: BRAZILIAN_MINIMUM_WAGE }
      validates :responsabilities, presence: true, length: { minimum: 50 }
      validates :benefits, presence: true, length: { minimum: 50 }

      default_scope -> { order created_at: :desc }

      def reject! feedback = nil
        update_attribute :status, :rejected
        update_attribute :feedback, feedback if feedback
      end

      def reject_with_default_feedback!
        update_attribute :status, :rejected
        update_attribute :feedback, I18n.t('activerecord.attributes.job/application/offer.accepted_another_offer')
      end

      def accept! feedback = nil
        update_attribute :status, :accepted
        update_attribute :feedback, feedback if feedback
      end

      private

      def whether_it_starts_in_the_future
        return if start_date_is_in_the_future?

        errors.add :start_date, :retroactive
      end

      def start_date_is_in_the_future?
        start_date && start_date > Date.today
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def after_sign_in_path_for resource
    return hunter_dashboard_path if resource.class.name == 'HeadHunter'
    return seeker_dashboard_path if resource.class.name == 'JobSeeker'
  end

  def after_sign_out_path_for _resource
    root_path
  end

  protected

  def devise_parameter_sanitizer
    if resource_class == HeadHunter
      HeadHunter::ParameterSanitizer.new HeadHunter, :head_hunter, params
    else
      JobSeeker::ParameterSanitizer.new JobSeeker, :job_seeker, params
    end
  end
end

app/controllers/hunter/applications_controller.rb
# frozen_string_literal: true

module Hunter
  class ApplicationsController < BaseController
    before_action :check_head_hunter, except: %i[index]

    def index
      @applications = current_head_hunter.applications.ongoing
    end

    def show
      @applicant = @application.job_seeker
    end

    def standout
      @application.update standout: @application.standout.!
      redirect_to request.referer
    end

    def rejection; end

    def reject
      if @application.update rejection_params
        flash[:success] = t 'flash.application_rejected'
        redirect_to hunter_applications_path
      else
        render :rejection
      end
    end

    private

    def rejection_params
      params.require(:job_application).permit :rejection_feedback
    end

    def check_head_hunter
      @application = Job::Application.find params[:id] || params[:application_id]
      return if @application.head_hunter == current_head_hunter

      flash[:danger] = t 'flash.unauthorized'
      redirect_to hunter_applications_path
    end
  end
end

app/controllers/seeker/applications_controller.rb
# frozen_string_literal: true

module Seeker
  class ApplicationsController < BaseController
    before_action :check_active_job, only: %i[new create]
    before_action :check_if_already_applied, only: %i[new create]
    before_action :check_applicant, only: %i[show]

    def index
      @applications = current_job_seeker.applications
    end

    def show
      @offers = @application.offers
    end

    def new
      @application = Job::Application.new
    end

    def create
      @application = build_application

      if @application.save
        flash[:success] = t 'flash.created',
                            resource: t('activerecord.models.job/application.one')
        redirect_to seeker_jobs_path
      else
        render :new
      end
    end

    private

    def build_application
      application = Job::Application.new application_params
      application.job = @job
      application.job_seeker = current_job_seeker
      application
    end

    def application_params
      params.require(:job_application).permit :cover_letter
    end

    def check_active_job
      @job = Job.find params[:job_id]
      return if @job.active?

      flash[:danger] = t 'flash.inactive_job'
      redirect_to seeker_jobs_path
    end

    def check_if_already_applied
      return unless current_job_seeker.already_applied? params[:job_id]

      flash[:danger] = t 'flash.already_applied'
      redirect_to seeker_job_path(@job)
    end

    def check_applicant
      @application = Job::Application.find params[:id]
      return if @application.job_seeker == current_job_seeker

      flash[:danger] = t 'flash.unauthorized'
      redirect_to seeker_applications_path
    end
  end
end

app/controllers/seeker/base_controller.rb
# frozen_string_literal: true

module Seeker
  class BaseController < ApplicationController
    before_action :authenticate_job_seeker!
    before_action :check_profile

    private

    def check_profile
      redirect_to new_seeker_profile_path unless current_job_seeker.profile?
    end
  end
end

app/controllers/seeker/dashboard_controller.rb
# frozen_string_literal: true

module Seeker
  class DashboardController < BaseController
    def index; end
  end
end

app/controllers/seeker/jobs_controller.rb
# frozen_string_literal: true

module Seeker
  class JobsController < BaseController
    before_action :check_active_job, only: %i[show]

    def index
      if params[:search]
        search_jobs
      else
        @jobs = Job.active
      end
    end

    def show; end

    private

    def search_jobs
      @jobs = Job.active.by_title_or_description params[:search]
      return unless @jobs.empty?

      @jobs = Job.active
      flash.now[:info] = t 'flash.job_not_found'
    end

    def check_active_job
      @job = Job.find params[:id]
      return if @job.active?

      flash[:danger] = t 'flash.inactive_job'
      redirect_to seeker_jobs_path
    end
  end
end

app/controllers/seeker/offers_controller.rb
# frozen_string_literal: true

module Seeker
  class OffersController < BaseController
    skip_before_action :verify_authenticity_token, only: %i[accept reject]

    before_action :check_job_seeker, only: %i[show accept reject]
    before_action :check_status, only: %i[accept reject]
    before_action :reject_ongoing_offers, only: %i[accept]

    def index
      @offers = current_job_seeker.offers
    end

    def show; end

    def accept
      @offer.accept! params[:feedback]

      flash[:success] = t 'flash.offer_accepted'
      redirect_to request.referer
    end

    def reject
      @offer.reject! params[:feedback]

      flash[:success] = t 'flash.offer_rejected'
      redirect_to request.referer
    end

    private

    def check_job_seeker
      @offer = Job::Application::Offer.find params[:id] || params[:offer_id]
      return if @offer.job_seeker == current_job_seeker

      flash[:danger] = t 'flash.unauthorized'
      redirect_to seeker_offers_path
    end

    def check_status
      return if @offer.ongoing?

      flash[:danger] = t 'flash.closed_offer'
      redirect_to seeker_offer_path(@offer)
    end

    def reject_ongoing_offers
      @ongoing_offers = current_job_seeker.offers.ongoing
      @rejected_offers = @ongoing_offers.filter { |offer| offer != @offer }
      @rejected_offers.each(&:reject_with_default_feedback!)
    end
  end
end

app/controllers/seeker/profiles_controller.rb
# frozen_string_literal: true

module Seeker
  class ProfilesController < BaseController
    before_action :load_profile, only: %i[show edit update]
    before_action :check_profile, only: %i[new create]

    def show; end

    def new
      flash.clear
      flash.now[:info] = t 'flash.fill_out_profile'
      @profile = JobSeeker::Profile.new
    end

    def create
      @profile = JobSeeker::Profile.new profile_params
      @profile.job_seeker = current_job_seeker

      if @profile.save
        flash[:success] = t 'devise.registrations.signed_up'
        redirect_to seeker_dashboard_path
      else
        render :new
      end
    end

    def edit; end

    def update
      if @profile.update profile_params
        flash[:success] = t 'flash.updated',
                            resource: t('activerecord.models.job_seeker/profile.one')
        redirect_to seeker_show_profile_path
      else
        render :edit
      end
    end

    private

    def profile_params
      params.require(:job_seeker_profile).permit :date_of_birth, :high_school,
                                                 :college, :degrees, :courses,
                                                 :interests, :bio, :avatar,
                                                 :work_experience
    end

    def load_profile
      @profile = current_job_seeker.profile
    end

    def check_profile
      redirect_to seeker_show_profile_path if current_job_seeker.profile?
    end
  end
end

app/controllers/seeker/registrations_controller.rb
# frozen_string_literal: true

module Seeker
  class RegistrationsController < Devise::RegistrationsController
    include Accessible
    skip_before_action :check_user, except: %i[new create]
  end
end

app/controllers/seeker/sessions_controller.rb
# frozen_string_literal: true

module Seeker
  class SessionsController < Devise::SessionsController
    include Accessible
    skip_before_action :check_user, only: :destroy
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  DATE_REGEX = /\d{4}-\d{2}-\d{2}/.freeze
end

app/views/seeker/applications/_feedback_form.html.erb
<%= form_with local: true, html: { method: :patch } do |f| %>
  <div class='form-group'>
    <%= f.label :feedback, t('views.job_seekers/offers.your_feedback') %>
    <%= f.text_area :feedback, class: 'form-control' %>
  </div>

  <%= f.submit t('views.actions.accept'), class: 'btn btn-primary',
               data: { confirm: t('views.messages.accept_offer', date: l(offer.start_date)) },
               formaction: seeker_offer_accept_path(offer) %>
  <%= f.submit t('views.actions.reject'), class: 'btn btn-danger',
               data: { confirm: t('views.messages.reject_offer') },
               formaction: seeker_offer_reject_path(offer) %>
<% end %>

app/views/seeker/applications/_form.html.erb
<%= form_with model: @application, url: yield(:resource_path), local: true,
              html: { method: yield(:method) } do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class='form-group'>
    <%= f.label :cover_letter %>
    <%= f.text_area :cover_letter, required: true, minlength: 50, class: 'form-control' %>
  </div>

  <%= f.submit t('views.actions.send'), class: 'btn btn-primary' %>
<% end %>

app/views/seeker/applications/_offers.html.erb
<section class='contents'>

  <% if @offers.empty? %>
    <p class="empty_resource"><%= t('views.jobs/applications/offers.empty_resource') %></p>
  <% else %>
    <dl class="offer_feed col-12">
      <h2 class="offer_feed_title">
        <%= t('activerecord.models.job/application/offer.other') %>
      </h2>

      <% @offers.each do |offer| %>
        <div id="offer-<%= offer.id %>" class="offer <%= offer.status %>_offer">
          <dt class="offer_head">
            <span class="offer_creator">
              <%= image_tag url_for(offer.head_hunter.avatar),
                alt: offer.head_hunter.resolve_name,
                class: 'offerer_avatar' %>

              <span class="offerer_name">
                <%= offer.head_hunter.resolve_name %>
              </span>
            </span>

            <span class="offer_timestamp">
              <%= l(offer.created_at, format: :long) %>
            </span>
          </dt>

          <div class="offer_overview">
            <span>
              <dt><%= t('activerecord.attributes.job/application/offer.status') %>:</dt>
              <dd> <%= t("activerecord.attributes.job/application/offer/status.#{offer.status}") %> </dd>
            </span>

            <span>
              <dt><%= t('activerecord.attributes.job/application/offer.start_date') %>:</dt>
              <dd> <%= l(offer.start_date) %> </dd>
            </span>

            <span>
              <dt><%= t('activerecord.attributes.job/application/offer.salary') %>:</dt>
              <dd> <%= number_to_currency(offer.salary) %> </dd>
            </span>
          </div>

          <dt><%= t('activerecord.attributes.job/application/offer.responsabilities') %>:</dt>
          <dd class="indent"> <%= offer.responsabilities %> </dd>

          <dt><%= t('activerecord.attributes.job/application/offer.benefits') %>:</dt>
          <dd class="indent"> <%= offer.benefits %> </dd>

          <% if offer.expectations.present? %>
            <dt><%= t('activerecord.attributes.job/application/offer.expectations') %>:</dt>
            <dd class="indent"> <%= offer.expectations %> </dd>
          <% end %>

          <% if offer.bonus.present? %>
            <dt><%= t('activerecord.attributes.job/application/offer.bonus') %>:</dt>
            <dd class="indent"> <%= offer.bonus %> </dd>
          <% end %>

          <% unless offer.ongoing? %>
            <% if offer.feedback.present? %>
              <dt><%= t('activerecord.attributes.job/application/offer.feedback') %>:</dt>
              <dd class="indent"> <%= offer.feedback %> </dd>
            <% end %>
          <% else %>
            <%= render 'feedback_form', offer: offer %>
          <% end %>

        </div>
      <% end %>
    </dl>
  <% end %>

</section>

app/views/seeker/applications/index.html.erb
<main class='row'>
  <div class='col-md-12'>
    <nav class='context_navigation'>
      <%= link_to t('views.navigation.go_back'), :back, class: 'btn btn-outline-secondary' %>
    </nav>

    <header class='header'>
      <h1><%= t('activerecord.models.job/application.other') %></h1>

      <p><%= t('views.job_seekers/applications.description') %></p>
    </header>

    <section class='contents'>

      <% if @applications.empty? %>
        <p class="empty_resource"><%= t('views.job_seekers/applications.empty_resource') %></p>
      <% else %>

      <table class="col index_table">
          <thead class="index_table_head">
            <tr class="index_table_row">
              <th><%= t('activerecord.attributes.job.title') %></th>
              <th><%= t('activerecord.attributes.job.expires_on') %></th>
              <th><%= t('activerecord.attributes.job/application.status') %></th>
              <th></th>
            </tr>
          </thead>

          <tbody class="index_table_body">
            <% @applications.each do |application| %>
              <tr class="index_table_row" id="application-<%= application.id %>">
                <td>
                  <%= link_to application.job.title, seeker_job_path(application.job) %>
                </td>
                <td>
                  <span class="status_dot <%= application.job.active? ?
                                                'active_dot' :
                                                'inactive_dot' %>">
                  </span>
                  <%= l(application.job.expires_on) %>
                </td>
                <td>
                  <span class="status_dot <%= application.rejected? ?
                                                'inactive_dot' :
                                                'active_dot' %>">
                  </span>
                  <%= application.status %>
                </td>
                <td>
                  <%= link_to t('views.navigation.details'),
                              seeker_application_path(application),
                              id: "details-#{application.id}" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>

    </section>

    <div class='actions mt-4'>
    </div>
  </div>
</main>

app/views/seeker/applications/new.html.erb
<% provide(:resource_path, seeker_job_applications_path(@job)) %>
<% provide(:method, :post) %>

<main class='row'>
  <div class='col-md-12'>
    <nav class='context_navigation'>
      <%= link_to t('views.navigation.go_back'), seeker_job_path(@job), class: 'btn btn-outline-secondary' %>
    </nav>

    <header class='header'>
      <h1><%= t('views.job_seekers/applications.create') %></h1>

      <p><%= t('views.job_seekers/applications.context', job_title: @job.title) %></p>
    </header>

    <section class='contents'>
      <%= render 'form' %>
    </section>

  </div>
</main>

app/views/seeker/applications/show.html.erb
<main class='row'>
  <div class='col-md-12'>
    <nav class='context_navigation'>
      <%= link_to t('views.navigation.go_back'), seeker_applications_path, class: 'btn btn-outline-secondary' %>
    </nav>

    <header class='header'>
      <h1>
        <%= "#{@application.job.position} #{t('views.support.of')} #{@application.job.title}" %>
      </h1>

      <h2 class="application_status <%= @application.rejected? ? 'rejected_application' : 'ongoing_application' %>">
        <%= "#{t('activerecord.attributes.job/application.status')}: #{@application.status}" %>
      </h2>

    </header>

    <section class='contents row'>
      <dl class="col">
        <dt><%= t('activerecord.attributes.job/application.cover_letter') %>:</dt>
        <dd class="indent"> <%= @application.cover_letter %> </dd>
      </dl>
    </section>

    <% if @application.rejected? %>
      <section class='contents row'>
        <dl class="col">
          <dt><%= t('activerecord.attributes.job/application.rejection_feedback') %>:</dt>
          <dd class="indent"> <%= @application.rejection_feedback %> </dd>
        </dl>
      </section>
    <% end %>

    <%= render 'offers' %>

  </div>
</main>